# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aditya/Desktop/Aditya/TAMU/Fall25/CSCE_654/Project/MultiBlockBPE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aditya/Desktop/Aditya/TAMU/Fall25/CSCE_654/Project/MultiBlockBPE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aditya/Desktop/Aditya/TAMU/Fall25/CSCE_654/Project/MultiBlockBPE/CMakeFiles /Users/aditya/Desktop/Aditya/TAMU/Fall25/CSCE_654/Project/MultiBlockBPE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aditya/Desktop/Aditya/TAMU/Fall25/CSCE_654/Project/MultiBlockBPE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MultiBlockBPE

# Build rule for target.
MultiBlockBPE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultiBlockBPE
.PHONY : MultiBlockBPE

# fast build rule for target.
MultiBlockBPE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/build
.PHONY : MultiBlockBPE/fast

src/DLLToken.o: src/DLLToken.cpp.o
.PHONY : src/DLLToken.o

# target to build an object file
src/DLLToken.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/DLLToken.cpp.o
.PHONY : src/DLLToken.cpp.o

src/DLLToken.i: src/DLLToken.cpp.i
.PHONY : src/DLLToken.i

# target to preprocess a source file
src/DLLToken.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/DLLToken.cpp.i
.PHONY : src/DLLToken.cpp.i

src/DLLToken.s: src/DLLToken.cpp.s
.PHONY : src/DLLToken.s

# target to generate assembly for a file
src/DLLToken.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/DLLToken.cpp.s
.PHONY : src/DLLToken.cpp.s

src/Token.o: src/Token.cpp.o
.PHONY : src/Token.o

# target to build an object file
src/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/Token.cpp.o
.PHONY : src/Token.cpp.o

src/Token.i: src/Token.cpp.i
.PHONY : src/Token.i

# target to preprocess a source file
src/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/Token.cpp.i
.PHONY : src/Token.cpp.i

src/Token.s: src/Token.cpp.s
.PHONY : src/Token.s

# target to generate assembly for a file
src/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/Token.cpp.s
.PHONY : src/Token.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiBlockBPE.dir/build.make CMakeFiles/MultiBlockBPE.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MultiBlockBPE"
	@echo "... src/DLLToken.o"
	@echo "... src/DLLToken.i"
	@echo "... src/DLLToken.s"
	@echo "... src/Token.o"
	@echo "... src/Token.i"
	@echo "... src/Token.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

